[book]
authors = ["Isawan Millican"]
language = "en"
src = "src"
title = "terrashine"

[output.html]
git-repository-url = "https://github.com/Isawan/terrashine"
edit-url-template = "https://github.com/Isawan/terrashine/edit/main/docs/{path}"
hash-files = true
site-url = "/terrashine/"
